FROM node:24-alpine

ENV NODE_ENV=production

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@11.6.0 --activate

COPY server/package.json server/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY server ./

EXPOSE 3000

CMD ["pnpm", "start-server"]
